services:
  - type: worker
    name: levelup-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATA_FILE
        value: /data/data.json

    disk:
      name: bot-data
      mountPath: /data
      sizeGB: 1
